<?php

/**
 * This is the model base class for the table "payment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Payment".
 *
 * Columns in table "payment" available as properties of the model,
 * followed by relations of table "payment" available as properties of the model.
 *
 * @property integer $payment_id
 * @property integer $user_id
 * @property integer $order_id
 * @property integer $wedding_id
 * @property integer $album_id
 * @property string $transaction_id
 * @property string $payment_amount
 * @property string $currency_type
 * @property string $payment_mode
 * @property string $payment_status
 * @property string $payment_message
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 * @property string $field1
 * @property string $field2
 *
 * @property UserDetail $user
 */
abstract class BasePayment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'payment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Payment|Payments', $n);
	}

	public static function representingColumn() {
		return 'transaction_id';
	}

	public function rules() {
		return array(
			array('user_id, order_id, wedding_id, album_id, transaction_id, payment_amount, currency_type, payment_mode, payment_status, payment_message, created_at, field1, field2', 'required'),
			array('user_id, order_id, wedding_id, album_id', 'numerical', 'integerOnly'=>true),
			array('transaction_id, payment_amount, currency_type, payment_mode, payment_status, field1, field2', 'length', 'max'=>100),
			array('payment_message', 'length', 'max'=>255),
			array('status', 'length', 'max'=>1),
			array('updated_at', 'safe'),
			array('updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('payment_id, user_id, order_id, wedding_id, album_id, transaction_id, payment_amount, currency_type, payment_mode, payment_status, payment_message, created_at, updated_at, status, field1, field2', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'UserDetail', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'payment_id' => Yii::t('app', 'Payment Id'),
			'user_id' => null,
			'order_id' => Yii::t('app', 'Order Id'),
			'wedding_id' => Yii::t('app', 'Wedding Id'),
			'album_id' => Yii::t('app', 'Album Id'),
			'transaction_id' => Yii::t('app', 'Transaction Id'),
			'payment_amount' => Yii::t('app', 'Payment Amount'),
			'currency_type' => Yii::t('app', 'Currency Type'),
			'payment_mode' => Yii::t('app', 'Payment Mode'),
			'payment_status' => Yii::t('app', 'Payment Status'),
			'payment_message' => Yii::t('app', 'Payment Message'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			//'field1' => Yii::t('app', 'Field1'),
		//	'field2' => Yii::t('app', 'Field2'),
			'user' => Yii::t('app', 'User Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('payment_id', $this->payment_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('wedding_id', $this->wedding_id);
		$criteria->compare('album_id', $this->album_id);
		$criteria->compare('transaction_id', $this->transaction_id, true);
		$criteria->compare('payment_amount', $this->payment_amount, true);
		$criteria->compare('currency_type', $this->currency_type, true);
		$criteria->compare('payment_mode', $this->payment_mode, true);
		$criteria->compare('payment_status', $this->payment_status, true);
		$criteria->compare('payment_message', $this->payment_message, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('field1', $this->field1, true);
		$criteria->compare('field2', $this->field2, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}