<?php

/**
 * This is the model base class for the table "color_theme".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ColorTheme".
 *
 * Columns in table "color_theme" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $color_id
 * @property string $wedding_id
 * @property string $main_color_code
 * @property string $accent_color_code
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 *
 */
abstract class BaseColorTheme extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'color_theme';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ColorTheme|ColorThemes', $n);
	}

	public static function representingColumn() {
		return 'wedding_id';
	}

	public function rules() {
		return array(
			array('wedding_id, main_color_code, accent_color_code, created_at', 'required'),
			array('wedding_id', 'length', 'max'=>10),
			array('main_color_code, accent_color_code', 'length', 'max'=>50),
			array('status', 'length', 'max'=>1),
			array('updated_at', 'safe'),
			array('updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('color_id, wedding_id, main_color_code, accent_color_code, created_at, updated_at, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'color_id' => Yii::t('app', 'Color'),
			'wedding_id' => Yii::t('app', 'Wedding'),
			'main_color_code' => Yii::t('app', 'Main Color Code'),
			'accent_color_code' => Yii::t('app', 'Accent Color Code'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('color_id', $this->color_id);
		$criteria->compare('wedding_id', $this->wedding_id, true);
		$criteria->compare('main_color_code', $this->main_color_code, true);
		$criteria->compare('accent_color_code', $this->accent_color_code, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}