<?php

/**
 * This is the model base class for the table "accomodation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Accomodation".
 *
 * Columns in table "accomodation" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $accomodation_id
 * @property integer $user_id
 * @property string $accom_name
 * @property string $accom_address
 * @property string $accom_web_url
 * @property string $accom_desc
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 * @property string $field1
 * @property string $field2
 *
 */
abstract class BaseAccomodation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'accomodation';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Accomodation|Accomodations', $n);
	}

	public static function representingColumn() {
		return 'accom_name';
	}
	

	public function rules() {
		return array(
			array('user_id, accom_name, accom_address, accom_web_url, accom_desc, created_at, field1, field2', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('accom_name', 'length', 'max'=>255),
			array('accom_web_url', 'length', 'max'=>350),
			array('status', 'length', 'max'=>1),
			array('field1, field2', 'length', 'max'=>100),
			array('updated_at', 'safe'),
			array('updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('accomodation_id, user_id, accom_name, accom_address, accom_web_url, accom_desc, created_at, updated_at, status, field1, field2', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'accomodation_id' => Yii::t('app', 'Accomodation Id'),
			'user_id' => Yii::t('app', 'User Name'),
			'accom_name' => Yii::t('app', 'Name'),
			'accom_address' => Yii::t('app', 'Address'),
			'accom_web_url' => Yii::t('app', 'Web Url'),
			'accom_desc' => Yii::t('app', 'Desc'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'field1' => Yii::t('app', 'Field1'),
			'field2' => Yii::t('app', 'Field2'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('accomodation_id', $this->accomodation_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('accom_name', $this->accom_name, true);
		$criteria->compare('accom_address', $this->accom_address, true);
		$criteria->compare('accom_web_url', $this->accom_web_url, true);
		$criteria->compare('accom_desc', $this->accom_desc, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('field1', $this->field1, true);
		$criteria->compare('field2', $this->field2, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}