<?php

/**
 * This is the model base class for the table "album_photo_gallery".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AlbumPhotoGallery".
 *
 * Columns in table "album_photo_gallery" available as properties of the model,
 * followed by relations of table "album_photo_gallery" available as properties of the model.
 *
 * @property integer $album_photo_id
 * @property integer $album_id
 * @property integer $user_id
 * @property string $photo_image
 * @property string $caption
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 *
 * @property Album $album
 * @property UserDetail $user
 */
abstract class BaseAlbumPhotoGallery extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'album_photo_gallery';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AlbumPhotoGallery|AlbumPhotoGalleries', $n);
	}

	public static function representingColumn() {
		return 'photo_image';
	}

	public function rules() {
		return array(
			array('album_id, user_id, photo_image, caption, created_at', 'required'),
			array('album_id, user_id', 'numerical', 'integerOnly'=>true),
			array('photo_image, caption', 'length', 'max'=>100),
			array('status', 'length', 'max'=>1),
			array('updated_at', 'safe'),
			array('updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('album_photo_id, album_id, user_id, photo_image, caption, created_at, updated_at, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'album' => array(self::BELONGS_TO, 'Album', 'album_id'),
			'user' => array(self::BELONGS_TO, 'UserDetail', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'album_photo_id' => Yii::t('app', 'Album Photo'),
			'album_id' => null,
			'user_id' => null,
			'photo_image' => Yii::t('app', 'Photo Image'),
			'caption' => Yii::t('app', 'Caption'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'album' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('album_photo_id', $this->album_photo_id);
		$criteria->compare('album_id', $this->album_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('photo_image', $this->photo_image, true);
		$criteria->compare('caption', $this->caption, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}