// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var brick;
    brick = "<div class='brick small'><div class='delete'>&times;</div></div>";
    $(document).on("click touchend", ".gridly .brick", function(event) {
      var $this, size;
      event.preventDefault();
      event.stopPropagation();
      $this = $(this);
      $this.toggleClass('small');
      $this.toggleClass('large');
      if ($this.hasClass('small')) {
        size = 140;
      }
      if ($this.hasClass('large')) {
        size = 300;
      }
      $this.data('width', size);
      $this.data('height', size);
      return $('.gridly').gridly('layout');
    });
    $(document).on("click", ".gridly .delete", function(event) {
      var $this;
      event.preventDefault();
      event.stopPropagation();
      $this = $(this);
      var addBrick=$this.closest('.brick').find('h5').text();
      $('.delgridly').append("<div class='brick small'><h5>"+addBrick+"</h5><div class='add'>Add</div></div>");
      $this.closest('.brick').remove();
      return $('.gridly').gridly();
    });
    $(document).on("click", ".add", function(event) {
      event.preventDefault();
      event.stopPropagation();
       $this = $(this);
      var brickText=$this.closest('.brick').find('h5').text();
      var totalLength=($('.line').length + parseInt(1));
      $('.gridly').append("<div class='brick small line' id="+totalLength+"><h5>"+brickText+"</h5><div class='delete'>&times;</div></div>");
      $this.closest('.brick').remove();
      return $('.gridly').gridly();
    });
      $(document).on("click", "#addAlbum", function(event) {
      event.preventDefault();
      event.stopPropagation();
       var totalLength=($('.line').length + parseInt(1));
      var customField = $('#custom_album_input').val();
      $('.gridly').append("<div class='brick small line' id="+totalLength+"><h5>"+customField+"</h5><div class='permanent'>&times;</div></div>");
      $('#custom_album_input').val("");
      return $('.gridly').gridly();
    });
     $(document).on("click", ".permanent", function(event) {
      event.preventDefault();
      event.stopPropagation();
       $this = $(this);
       $this.closest('.brick').remove();
      return $('.gridly').gridly();
    });
    return $('.gridly').gridly();
  });
}).call(this);
